---
title: 'Tidy Tuesday #3'
author: "Brant Newman"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
theme_set(theme_minimal()) # My favorite ggplot() theme :)
```

## Data choice 2: Alternative fuel stations

```{r}
stations <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-01/stations.csv')
```

Read more about the Alternative fuel stations data, including definitions of variables, [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-01/readme.md). 


```{r}
library(tidyverse)     # for data cleaning and plotting
library(gardenR)       # for Lisa's garden data
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(palmerpenguins)# for Palmer penguin data
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
theme_set(theme_minimal())
```


```{r}
stationsPA <- stations %>% 
  filter(STATE == "PA") 
```

```{r}
PA <- get_stamenmap(
  bbox = c(left = -80.586, bottom = 39.550, right = -74.598, top = 42.318), 
  maptype = "toner",
  zoom = 7)

ggmap(PA) +
  geom_point(data = stationsPA, 
             aes(x = X, y = Y), 
             color = "navyblue",
             alpha = 1, 
             size = 1) +
  labs(title = "Alternative Fuel Stations in PA", caption = "Made by Brant Newman")
  theme_map()
```





